### PR TITLE
Basic improve to structure

### PR DESCRIPTION
**Pull request by thanos-do**
1. You need to take care the structure (for instance where your class open & close).
2. Also you can use :selectors.
3. Don't be very specific with px (aka setting img to have width 432px and height 331px) you will regret it when you go to build responsive.
4. Let your elements "breath" you shrink them too much no need to do that :D 

PS: I didn't do any responsive but the concept is when you reach tablet (<=768px) make it a block element and remove flex.

### CODE REVIEW

**Comment by DespinaXenou** [comment]
> This pull request is being automatically deployed with Vercel ([learn more](https://vercel.link/github-learn-more)). To see the status of your deployment, click below or on the icon next to each commit.
> 
> 🔍 Inspect: https://vercel.com/superozzy/interactive-component-card/JBrXbWmnFhcpLMSwxbKSjmFSHAdd ✅ Preview: https://interactive-component-card-git-fork-thanos-do-patch-2-superozzy.vercel.app

**Comment by DespinaXenou** [comment]
> 1. You need to take care the structure (for instance where your class open & close).
> 2. Also you can use :selectors.
> 3. Don't be very specific with px (aka setting img to have width 432px and height 331px) you will regret it when you go to build responsive.
> 4. Let your elements "breath" you shrink them too much no need to do that :D
> 
> PS: I didn't do any responsive but the concept is when you reach tablet (<=768px) make it a block element and remove flex.

**Comment by DespinaXenou** [comment]
> 1. You need to take care the structure (for instance where your class open & close).
> 2. Also you can use :selectors.
> 3. Don't be very specific with px (aka setting img to have width 432px and height 331px) you will regret it when you go to build responsive.
> 4. Let your elements "breath" you shrink them too much no need to do that :D
> 
> PS: I didn't do any responsive but the concept is when you reach tablet (<=768px) make it a block element and remove flex.

hey ,reaaly aprreciate your time!I will check it out for the next projects for sure.if you have any other advice it will be welcomed!

**Comment by thanos-do** [comment]
Μπορείς να με χρησιμοποιήσεις σαν reviewer όπου θες γιατι να μπώ μόνος να δώ θα το ξεχάσω κατα 99%.
Έχω υπάρξει και εγώ στην θέση σου σε αυτό το στάδιο οπότε δεν χρειάζεται να ευχαριστείς ;)

**Comment by DespinaXenou** [comment]
> Μπορείς να με χρησιμοποιήσεις σαν reviewer όπου θες γιατι να μπώ μόνος να δώ θα το ξεχάσω κατα 99%. Έχω υπάρξει και εγώ στην θέση σου σε αυτό το στάδιο οπότε δεν χρειάζεται να ευχαριστείς ;)

Εγινε σιγουρα θα σε χρησιμποιησω,οχι οχι οντως ευχαριστω δεν το κανουν ολοι αυτο!

**Pull request closed without merging**
